#!/bin/sh
if [[ $1 == remove ]]; then

    echo "Cleaning keyboard cache..."
    rm -rf /var/mobile/Library/Caches/com.apple.keyboards/

    declare -a cydia
    cydia=($CYDIA)
    if [[ ${CYDIA+@} ]]; then
        eval "echo 'finish:reload' >&${cydia[0]}"
    else
        echo "Please respring your device."
    fi
fi
