#!/bin/sh
if [[ $1 == install || update ]]; then

	echo "Cleaning keyboard cache..."
	
	cd /var/mobile/Library/Caches
	rm -Rf ./com.apple.keyboards/
	
	cd /var/mobile/Library/Preferences/
	if [ -f  com.hiraku.optimizedzhuyin.plist ]; then
	    mv -f com.hiraku.optimizedzhuyin.plist tw.hiraku.optimizedzhuyin.plist
	fi
fi
